### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by ghost** [tuxphone/CubeCellRepeater#1]
Is there somehow a way to make it work with other channel names and other long range settings?

**Comment by tuxphone** [comment]
Hello,
i'm working on other settings, will make a commit today.

The channel name itself is of no importance for the CCRepeater, but meshtastic generates from it the channel number, which defines the resulting used frequency. So if you know your settings, you will be able to set your ChannelSettings and the CubeCell should repeat.

**Comment by ghost** [comment]
Yeah, but the probem is that even if I know the channel name, I don't know how to generate the channel and the frequency as I am not a coding expert........

I would like just to see an input channel name and the CubeCell will handle everything normally.

**Comment by tuxphone** [comment]
I got the necessary information for that, but it is still TO DO right now. I've just commited some changes to the code. It is using the original meshtastic definitions and types, so it's easier to work with the existing meshtastic code.

The repeater is still working fine with Channel 0 ("Default") and SF 12, CR 4/8, BW 0 (125kHz).

The Bandwidth is different from original meshtastic right now. The radio driver (radio.c) is using an array of Bandwidths instead of the actual bandwidths so i will need to translate the Bandwidth in kHz to the index (TO DO).

**Comment by tuxphone** [comment]
Good news!
Configure your channel name and your speed settings in MeshRadio.h, compile and you are done!

All settings are automatically set and your private channel should be repeated. I tested it with different names and speed settings and it worked for me. Please try and give feedback with any problems you have.
